### ISSUE TITLE
Error i can't describe

### ISSUE THREAD

**Issue by jaylawl** [TheBukor/SkStuff#4]
Upgraded from Spigot 1.10.2 / Skript dev23 / SkStuff 1.6.3.9 to 1.11.2, same skript and SkStuff 1.6.4.1

skript will throw the error below out in console, rendering all scripts unloadable. nothing works.
```
[17:04:17 WARN]: [Skript] Task #62767 for Skript v2.2-dev23 generated an exception
java.lang.NoSuchMethodError: com.sk89q.worldguard.bukkit.WorldGuardPlugin.getFlagRegistry()Lcom/sk89q/worldguard/protection/flags/registry/FlagRegistry;
at me.TheBukor.SkStuff.SkStuff$4.parse(SkStuff.java:245) ~[?:?]
at me.TheBukor.SkStuff.SkStuff$4.parse(SkStuff.java:1) ~[?:?]
at ch.njol.skript.registrations.Classes.parseSimple(Classes.java:422) ~[?:?]
at ch.njol.skript.registrations.Classes.parse(Classes.java:451) ~[?:?]
at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:97) ~[?:?]
at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:86) ~[?:?]
at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:1) ~[?:?]
at ch.njol.skript.conditions.CondContains.init(CondContains.java:72) ~[?:?]
at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:249) ~[?:?]
at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176) ~[?:?]
at ch.njol.skript.lang.Condition.parse(Condition.java:83) ~[?:?]
at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:833) ~[?:?]
at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:513) ~[?:?]
at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:247) ~[?:?]
at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:245) ~[?:?]
at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:201) ~[?:?]
at ch.njol.skript.Skript$2.run(Skript.java:406) ~[?:?]
at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[craftbukkit.jar:git-Spigot-7d78b81-f9e0440]
at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [craftbukkit.jar:git-Spigot-7d78b81-f9e0440]
at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:730) [craftbukkit.jar:git-Spigot-7d78b81-f9e0440]
at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [craftbukkit.jar:git-Spigot-7d78b81-f9e0440]
at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [craftbukkit.jar:git-Spigot-7d78b81-f9e0440]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [craftbukkit.jar:git-Spigot-7d78b81-f9e0440]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
```

**Comment by jaylawl** [comment]
solved:

required update to worldguard 6.2. previously used worldguard version was 6.1.2 which caused the error. now everythign seems to be working.
